### ISSUE TITLE
Proxy is including CSP in headers

### ISSUE THREAD

**Issue by jin-ahn** [keattang/eks-auth-proxy#22]
Kuberenetes Dashboard is unable to fully load do to CSP being included by the proxy. Although the Dashboard is functional, the UI is unusable because of the unloaded js.
```
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src-attr 'none'"
```

The fix was was removing `app.use(helmet());` line in `index.js`
https://github.com/keattang/eks-auth-proxy/blob/4393f6ad4152a838b6c963cf5a6ce1411441ea81/src/index.js#L34

**Comment by keattang** [comment]
Apologies @jin-ahn I didn't see this issue come up. There is now a `--proxy-disable-csp-header` option thanks to @agutoli
