### ISSUE TITLE
aws-iam-authenticator deprecated.

### ISSUE THREAD

**Issue by llamahunter** [keattang/eks-auth-proxy#4]
I believe the aws cli command `aws eks get-token --cluster-name <cluster-name>` is the preferred replacement.

**Comment by keattang** [comment]
Thanks @llamahunter do you have more information/documentation on the deprecation?

**Comment by llamahunter** [comment]
https://aws.amazon.com/about-aws/whats-new/2019/05/amazon-eks-simplifies-kubernetes-cluster-authentication/

**Comment by keattang** [comment]
From what I understand, I don't think that `aws-iam-authenticator` is deprecated, there's just a more convenient method of getting the token. I believe that the authenticator is still required to run as a backend service in your cluster and so won't be going away any time soon.

Given that switching to the AWS CLI method would require installing python as well as the CLI, I think it's best to stay with the authenticator binary. 

Hopefully they release an equivalent method in the JS SDK and we can switch to using that when it comes out.
