### ISSUE TITLE
Add authentication endpoint to use with Nginx auth_request

### ISSUE THREAD

**Issue by nachomillangarcia** [keattang/eks-auth-proxy#5]
I liked so much this project. 

When trying to use this proxy as an external OAuth method (with the [auth_request](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html) directive from Nginx, I realized that there is no endpoint to verify authentication.

Nginx needs an endpoint that returns 403 or 401 if auth failed. The proxy only returns 302 to /login whatever the path is.

Would it be possible to add this kind of endpoint? That will make this project valid to use with any kind of external auth method in EKS, securing all kinds of ingresses automatically.

Thanks for your work, cheers!

**Comment by keattang** [comment]
Hey @nachomillangarcia this should be straight forward. 

Just to clarify though, are you looking for all routes to return 401/403 if not authenticated or are you looking for a specific route that returns 403/401 when not authenticated and the rest will continue to return 302?

**Comment by nachomillangarcia** [comment]
Hi (sorry for the late response)

Only one route is needed (i.e. /auth-request). It just has to check if the cookie is valid and return 200 in that case or 403/401 if it didn't work. Nginx then uses that status code to allow access or to redirect the user to a login page.

Here is the explanation of the mechanism:

> The ngx_http_auth_request_module module (1.5.4+) implements client authorization based on the result of a subrequest. If the subrequest returns a 2xx response code, the access is allowed. If it returns 401 or 403, the access is denied with the corresponding error code. Any other response code returned by the subrequest is considered an error.

**Comment by keattang** [comment]
@nachomillangarcia you there is now a `/login/check` route that will return a 200 if authenticated and a 401 if not. There's also some more info about routes in the README:
https://github.com/keattang/eks-auth-proxy#routes

**Comment by nachomillangarcia** [comment]
Thanks :) It works perfectly with Nginx auth.
 
One last suggestion, would it be possible to add the `Authorization` header to the response on `/login/check`? This way we can tell Nginx to pass this header to upstream services as Kubernetes Dashboard.

**Comment by keattang** [comment]
@nachomillangarcia I am uncertain whether this is safe as it would expose the auth token to any client with the cookie. How are you using nginx in combination with the auth proxy? Can you not rely on the auth proxy to pass the header upstream to the kubernetes dashboard?
